//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LittleDwarfsAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceList
    {
        public int Id { get; set; }
        public Nullable<int> Invoice { get; set; }
        public Nullable<System.DateTime> Weekending { get; set; }
        public Nullable<int> Timesheet { get; set; }
        public Nullable<double> HoursWorked { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> Cost { get; set; }
    }
}
